#!/bin/sh
set -e
if [ "$1" = configure ]; then
    if ! getent passwd cryptoguard >/dev/null; then
        adduser --system --group --home /var/lib/cryptoguard --no-create-home --disabled-login cryptoguard
    fi
fi
#DEBHELPER#
